services:
  indicators-service:
    build:
      context: ./indicators and signals
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./indicators and signals:/app
    environment:
      - FLASK_APP=calc.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    depends_on:
      - prediction-service
      - postgres-db  # Changed from db to postgres-db
    networks:
      - app-network

  prediction-service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ai:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - app-network

  project1-service:
    build:
      context: ./project1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db  # Changed from db to postgres-db
    networks:
      - app-network

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dians
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
